version: '3.8'

services:
  # FreedomBlaze service
  freedomblaze:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - CurrencyExchangeRateApi=362b90fce089784d1e47ec2fa26117c1
      - PhoenixConfig__Token=d577516c9a9e96b4fa95a8e8b7180c3c4d392175fb2e55b01f5e5bc629b5aa29
      - PhoenixConfig__Host=http://freedomblaze-phoenixd:9740
    volumes:
      - freedomblaze-keyring:/root/.aspnet/DataProtection-Keys
    networks:
      - freedom-blaze-network

  # Phoenixd service
  freedomblaze-phoenixd:
    build:
      context: ./src/submodules/phoenixd.NET/Phoenixd.NET/.docker/phoenixd
      dockerfile: Dockerfile
    ports:
      - "9741:9740"
    volumes:
      - freedomblaze-phoenixd-config:/root/.phoenix
    networks:
      - freedom-blaze-network

volumes:
  freedomblaze-keyring:
  freedomblaze-phoenixd-config:

networks:
  freedom-blaze-network:
    driver: bridge
