name: Build and deploy Docker Compose to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Log in to Docker Hub (if necessary for your Docker image)
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Set up Docker Buildx for multi-platform builds (if necessary)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build the Docker images and push to a container registry (Azure Container Registry or Docker Hub)
      - name: Build and Push Docker Compose
        run: |
          docker compose -f docker-compose.yml build
          docker compose -f docker-compose.yml push

      # Log in to Azure using GitHub secrets for Azure credentials
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      # Deploy to Azure App Service using Docker Compose
      - name: Deploy to Azure App Service using Docker Compose
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'freedomblazeapp'
          slot-name: 'Production'
          images: |
            freedomblaze:${{ github.sha }}
            phoenixd:${{ github.sha }}
          docker-compose: ./docker-compose.yml
