name: Build and deploy Docker Compose to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository including submodules
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: true

      # Initialize submodules
      - name: Initialize submodules
        run: git submodule update --init --recursive

      # Log in to Docker Hub (or ACR)
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build and push Docker images with Docker Compose
      - name: Build and Push Docker Compose
        run: |
          docker compose -f docker-compose.yml build
          docker compose -f docker-compose.yml push

      # Set up Python 64-bit
      - name: Set up Python 64-bit
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: 'x64'

      # Log in to Azure
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Docker Compose to Azure Web App for Containers using Azure CLI
      - name: Deploy Docker Compose to Azure Web App
        run: |
          az webapp config container set \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name freedomblazeapp \
            --multicontainer-config-type compose \
            --multicontainer-config-file docker-compose.yml
