name: Build and deploy Docker Compose to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository including submodules
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: true # Ensure submodules are initialized and updated

      # Initialize submodules
      - name: Initialize submodules
        run: git submodule update --init --recursive

      # Log in to Docker Hub (or ACR)
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build and push Docker images with Docker Compose
      - name: Build and Push Docker Compose
        run: |
          docker compose -f docker-compose.yml build
          docker compose -f docker-compose.yml push

      # Log in to Azure using client secret authentication
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy to Azure App Service using Docker Compose
      - name: Deploy to Azure App Service using Docker Compose
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'freedomblazeapp'
          slot-name: 'Production'
          images: |
            freedomblaze:${{ github.sha }}
            phoenixd:${{ github.sha }}
          docker-compose: ./docker-compose.yml
          
permissions:
  id-token: write # This allows the workflow to request OIDC tokens for authentication
  contents: read
